#!/bin/bash
set -e -E -u

TARGET_LOCALE=C.UTF-8
if [[ -z ${LC_ALL:-} ]]; then
    echo "setting LC_ALL!"
    echo "export LC_ALL=$TARGET_LOCALE" >> ~/.bashrc
    export LC_ALL=$TARGET_LOCALE
fi

cd $(dirname $0)

apt-get install elixir

mix local.hex --force
mix  hex.info
[[ -x ~/.mix/rebar ]] || mix local.rebar
mix deps.get --all
